### ISSUE TITLE
Better cropping with bird's eye 1/3 from top, bird entirely within the frame.

### ISSUE THREAD

**Issue by leavens** [adcrn/knest#22]
This is a minor issue, but sometimes the photo cropping, in an attempt to put the bird's eye in the center of the cropped photo, crops out the birds feet, at the bottom of the picture. The enhancement I would suggest is to try to place the bird entirely in the cropped picture and preferentially to place the bird's eye on a line in the center of the frame (left to right) and 1/3 from the top of the frame (on a line from top to bottom).

A complication is that often the entire bird is not actually visible (being occulded by a leaf or branch).

The issue might be that the bounding boxes for birds are not including all of the bird (legs and tail in particular).

The reason for this suggestion/enhancement is that I think it is often better if the photo looks like the viewer is looking up at the bird (as is often the case in reality, when the bird is above the photographer, say, in a tree).

**Comment by leavens** [comment]
Another possibility for the cropping is to omit it entirely, by just selecting the pictures and placing them in the processed directory; that way the user can crop them as they see fit.  More flexible would be to let the user have various options about cropping, one of which could be not to crop the picture at all, another to let the user specify the size (in pixels) of the cropped image and the rules (from a menu).

An example of the problem is the following 
![img_1022](https://user-images.githubusercontent.com/12302013/42423210-b6331bba-82c4-11e8-93ea-a8de59540c28.JPG)
image, processed by the program.  This doesn't cut off the bird's feet, but it doesn't allow me to crop the photo as I would like, with the bird's eye higher, as there is not much room below the bird's feet to do the crop, like the following.
![img_1022](https://user-images.githubusercontent.com/12302013/42423218-e40d50b4-82c4-11e8-8aa2-502b4e9972f2.JPG)

**Comment by leavens** [comment]
Another example, where the bird's legs are nearly chopped out of the frame by the program's crop. This is the crop made by the program:

![img_1086](https://user-images.githubusercontent.com/12302013/42423420-b2f8b7ae-82c7-11e8-86fc-79c9dc5a7954.JPG)

In this picture the birds legs are nearly cut off. In the original the bird's feet are hidden by the vegatation, but I would prefer a crop like the following.

![img_1086](https://user-images.githubusercontent.com/12302013/42423424-e12cb170-82c7-11e8-94c1-3b6f3298526c.JPG)

**Comment by adcrn** [comment]
@leavens: These changes have not been merged into master yet, but in regards to your first comment, we think we've come up something you may like. We'll let the pictures speak for themselves.

Original:
![img_3938](https://user-images.githubusercontent.com/9167686/42918997-de40b650-8add-11e8-88ed-a2b2bad491da.JPG)
Crop using f85756b:
![img_3938](https://user-images.githubusercontent.com/9167686/42919000-e0d94e68-8add-11e8-9341-f9b171117275.JPG)

Original:
![img_9740](https://user-images.githubusercontent.com/9167686/42918968-ab633974-8add-11e8-9e41-9580c7a5cc13.JPG)
Crop using f85756b:
![img_9740](https://user-images.githubusercontent.com/9167686/42918969-ad5243a6-8add-11e8-9fe8-7f9a4de4c00f.JPG)

Please note that not all pictures will experience a shift in viewpoint; this is due to the size of the bounding box returned from the detection stage. A fix in that stage would be intractable given the complexity of the code.

Concerning your second comment, the Advanced Settings screen (accessible through the gear icon) contains an option that allows you to disable cropping entirely, should you choose to do so.

![crop_op](https://user-images.githubusercontent.com/9167686/42919510-51c3ce6c-8ae0-11e8-934c-3fc0279162da.jpg)

This commit will be merged into master after additional testing and will be rolled into the v1.1 release as well.

**Comment by adcrn** [comment]
Not at the moment; we'll make a larger contribution to the master branch this weekend that includes work on #18, aka "the bird should be what is in focus".

**Comment by leavens** [comment]
Hi Alexander,

Great, I appreciate you working on it more. I'm ready to test whenever you
say the word (and tell me how).

        Regards,

        Gary T. Leavens
        437D Harris Center (Bldg. 116)
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens  phone: +1-407-823-4758
        leavens@cs.ucf.edu
